name: ROS2 Design
description: "Distilled design documents related to the ROS 2.0 effort"

baseurl: ""
url: http://design.ros2.org
repo: https://github.com/ros2/design

oauth_client_id: efa6dd8eae9106381720

markdown: kramdown
highlighter: rouge

kramdown:
   input: GFM

exclude:
 - CNAME
 - config.json
 - examples
 - Gemfile
 - LICENSE
 - README.md
 - vendor
